--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/simon/Pictures/wallpapers/Fantasy-Landscape.png"

-- Special
background="#080D15"
foreground="#ddcacc"
cursor="#ddcacc"

-- Colors
color0="#080D15"
color1="#63535A"
color2="#865B3C"
color3="#946C69"
color4="#A17985"
color5="#7C8381"
color6="#AD9296"
color7="#ddcacc"
color8="#9a8d8e"
color9="#63535A"
color10="#865B3C"
color11="#946C69"
color12="#A17985"
color13="#7C8381"
color14="#AD9296"
color15="#ddcacc"
