# Shell variables
# Generated by 'wal'
wallpaper='/home/simon/Pictures/wallpapers/Fantasy-Landscape.png'

# Special
background='#080D15'
foreground='#ddcacc'
cursor='#ddcacc'

# Colors
color0='#080D15'
color1='#63535A'
color2='#865B3C'
color3='#946C69'
color4='#A17985'
color5='#7C8381'
color6='#AD9296'
color7='#ddcacc'
color8='#9a8d8e'
color9='#63535A'
color10='#865B3C'
color11='#946C69'
color12='#A17985'
color13='#7C8381'
color14='#AD9296'
color15='#ddcacc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
